%% Aufgabe 1, 17032015
%   Schreibe ein Programm, welches eine Grafik wie folgende erzeugt( ein
%   Kreis mit P(0,0) und Radius von 1 mit einem Pfeil, der zum Mittelpunkt
%   zeigt und weist (0,0) hin.

x= linspace(-1,1,200);
y= 1- (x.^2);
kreis_oben = sqrt(y);
kreis_unten= -sqrt(y);

figure;
axis square;
kreis = plot(x,kreis_oben,...
             x,kreis_unten);
set(kreis, 'color', [0 1 0]);
set(gca,'xtick',[-1 0 1],...
        'ytick',[-1 0 1]);
text(-1,0,'\pi',...
    'fontsize',18,...
    'verticalAlignment','middle',...
    'horizontalAlignment','right');
text(0,1,'1/2 \pi',...
    'fontsize',18,...
    'verticalAlignment','bottom',...
    'horizontalAlignment','center');
text(1,0,'0',...
    'fontsize',18,...
    'verticalAlignment','middle',...
    'horizontalAlignment','left');
text(0,-1,'3/2 \pi',...
    'fontsize',18,...
    'verticalAlignment','top',...
    'horizontalAlignment','center');

xlim([-1.5 1.5]);
ylim([-1.5 1.5]);
annotation('textarrow',[0.65 0.52], [0.4 0.5],'String','(0,0)','fontsize',16);

%viele Formate:'-djpg','-deps','-dpng', usw
print('kreis.png','-dpng','-r300'); %-r300 zeigt die Auflösung
print('kreis.eps','-depsc'); %-deps ruft die EPS-Datei, c steht für Color

